# version: '3.8'

services:
  api:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./BackEnd/.env
    volumes:
      - ./BackEnd:/usr/app
      # - /usr/app/node_modules
    working_dir: /usr/app
    command: npm run start:dev
  
  mobile:
    build:
      context: ./Mobile
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "8081:8081"
      # - "19001:19001"
      # - "19002:19002"
    volumes:
      - ./Mobile:/app
      # - /app/node_modules
    working_dir: /app
    command: npx expo start --dev-client
    # command: npx expo start --web