services:
  api:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./BackEnd/.env
    # Sem volumes de código ou command override
    # healthcheck:
    #   # Testa se a API está realmente pronta para receber requisições
    #   test: ["CMD", "wget", "-q", "--spider", "http://localhost:3001/api"] # Crie uma rota /api ou /health no NestJS
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    networks:
      - app-network

  frontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./FrontEnd/.env
    # O depends_on agora espera a API estar "saudável" (healthcheck passar)
    depends_on:
      - api
      # api:
      #   condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
             
    