services:
  postgres:
    image: postgres:latest
    container_name: postgres_desafio
    restart: always
    environment:
      POSTGRES_USER: yuri
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: post_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
