
services:
  mongodb:
    image: mongo:latest
    container_name: desafio-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-example}
    restart: unless-stopped

  backend:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
      args:
        - MONGO_URI=${MONGO_URI}
        - JWT_SECRET=${JWT_SECRET}
    ports:
      - "3010:3010"
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./BackEnd:/usr/app
      - /usr/app/node_modules
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3010/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongodb_data: